name: Build BusyBox Static for MDM9607 (GCC 4.9)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Linaro GCC 4.9 Toolchain
      run: |
        # Download toolchain GCC 4.9.4 dari Linaro
        wget -c https://releases.linaro.org/components/toolchain/binaries/4.9-2017.01/arm-linux-gnueabihf/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabihf.tar.xz
        tar xf gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabihf.tar.xz
        # Tambahkan ke PATH
        echo "$(pwd)/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabihf/bin" >> $GITHUB_PATH
        
        # Verifikasi versi
        arm-linux-gnueabihf-gcc --version

    - name: Configure for static build (ARMv7-A for MDM9607)
      run: |
        export CROSS_COMPILE=arm-linux-gnueabihf-
        export ARCH=arm
        
        make defconfig
        
        # Konfigurasi static build
        echo "CONFIG_STATIC=y" >> .config
        echo "# CONFIG_FEATURE_SHARED_BUSYBOX is not set" >> .config
        
        # Nonaktifkan SHA HWACCEL (penting untuk ARM)
        sed -i 's/^CONFIG_SHA1_HWACCEL=y/# CONFIG_SHA1_HWACCEL is not set/' .config
        sed -i 's/^CONFIG_SHA256_HWACCEL=y/# CONFIG_SHA256_HWACCEL is not set/' .config
        
        make oldconfig

    - name: Build BusyBox
      run: |
        export CROSS_COMPILE=arm-linux-gnueabihf-
        export ARCH=arm
        
        make -j$(nproc) \
             CFLAGS="-Os -pipe -static -march=armv7-a -mfpu=vfpv4-d16 -mfloat-abi=hard" \
             LDFLAGS="-static" \
             SKIP_STRIP=n

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: busybox-mdm9607-gcc49
        path: busybox
